CREATE_SUBDIR_PER_RUN: True
server_file: ./server.py
client_file: ./client.py
config: ./config.yaml
data_dir: ../datasets/flamingo_generated/
work_dir: ./runs/mnist/
seed: 2024
batch_size: 64
test_batch_size: 64
lr: 0.001
weight_decay: 0.0001
max_epochs: 100
dropout: 0.5
momentum: 0.9
local_epochs: 1
num_clients: 15
num_training_clients: 5
method: fedavg
model_type: cnn
dataset_type: mnist
log_path: ./runs/mnist/2023-12-28-18-15-52/logs.log
verb: 1
run_dir: ./runs/mnist/2023-12-28-18-15-52
saved_config_dir: ./runs/mnist/2023-12-28-18-15-52/config.yaml
